Fix: change to 'unsigned int'
neo/renderer/Image_files.cpp:924:14: error: non-constant-expression cannot be narrowed from type 'unsigned int' to 'unsigned char' in initializer list [-Wc++11-narrowing]